/** @type {import('tailwindcss').Config} */
import daisyui from 'daisyui';

export default {
  content: ['./src/**/*.{js,jsx,ts,tsx}'],
  plugins: [daisyui],

  daisyui: {
    themes: [
      {
        mytheme: {
          primary: '#048bb1',
          'primary-content': 'oklch(98% 0.01 240)',
          secondary: 'oklch(70% 0.25 200)',
          'secondary-content': 'oklch(98% 0.01 200)',
          accent: 'oklch(65% 0.25 160)',
          'accent-content': 'oklch(98% 0.01 160)',
          neutral: 'oklch(50% 0.05 240)',
          'neutral-content': 'oklch(98% 0.01 240)',
          'base-100': 'oklch(98% 0.02 240)',
          'base-200': 'oklch(95% 0.03 240)',
          'base-300': 'oklch(92% 0.04 240)',
          'base-content': 'oklch(20% 0.05 240)',
          info: 'oklch(70% 0.2 220)',
          'info-content': 'oklch(98% 0.01 220)',
          success: 'oklch(65% 0.25 140)',
          'success-content': 'oklch(98% 0.01 140)',
          warning: 'oklch(80% 0.25 80)',
          'warning-content': 'oklch(20% 0.05 80)',
          error: 'oklch(65% 0.3 30)',
          'error-content': 'oklch(98% 0.01 30)',

          '--rounded-box': '1rem',
          '--rounded-btn': '0.25rem',
          '--rounded-badge': '0.5rem',
          '--animation-btn': '0.25s',
          '--animation-input': '0.2s',
          '--btn-focus-scale': '0.95',
          '--border-btn': '1px',
          '--tab-border': '1px',
          '--tab-radius': '0.5rem',
        },
      },
    ],
    fontFamily: {
      body: [
        'Open Sans',
        'ui-sans-serif',
        'system-ui',
        '-apple-system',
        'system-ui',
        'Segoe UI',
        'Roboto',
        'Helvetica Neue',
        'Arial',
        'Noto Sans',
        'sans-serif',
        'Apple Color Emoji',
        'Segoe UI Emoji',
        'Segoe UI Symbol',
        'Noto Color Emoji',
      ],
      sans: [
        'Open Sans',
        'ui-sans-serif',
        'system-ui',
        '-apple-system',
        'system-ui',
        'Segoe UI',
        'Roboto',
        'Helvetica Neue',
        'Arial',
        'Noto Sans',
        'sans-serif',
        'Apple Color Emoji',
        'Segoe UI Emoji',
        'Segoe UI Symbol',
        'Noto Color Emoji',
      ],
    },
  },
};
