# Generated by Django 5.1.5 on 2025-10-26 10:51

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflows', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='task_date_echeance',
            new_name='task_due_date',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='task_priorite',
            new_name='task_priority',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='task_statut',
            new_name='task_status',
        ),
        migrations.RenameField(
            model_name='workflow',
            old_name='nom',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='workflow',
            old_name='etat',
            new_name='status',
        ),
        migrations.AddField(
            model_name='task',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='task',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='workflow',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='workflow',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
