# Generated by Django 5.1.5 on 2025-10-26 13:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workflows', '0002_rename_task_date_echeance_task_task_due_date_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='task_due_date',
            new_name='task_date_echeance',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='task_priority',
            new_name='task_priorite',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='task_status',
            new_name='task_statut',
        ),
        migrations.RenameField(
            model_name='workflow',
            old_name='status',
            new_name='etat',
        ),
        migrations.RenameField(
            model_name='workflow',
            old_name='name',
            new_name='nom',
        ),
    ]
