"""
Django settings for backend project.

Generated by 'django-admin startproject' using Django 5.1.4.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

from pathlib import Path
import os
from dotenv import load_dotenv

BASE_DIR = Path(__file__).resolve().parent.parent
# MEDIA_ROOT and BACKEND_DIR are commented out to avoid overriding Minio/S3 storage.
# MEDIA_ROOT = os.path.join(BASE_DIR, "media")
# BACKEND_DIR = "backend/media/"

# Define the custom user model
AUTH_USER_MODEL = "users.User"

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = "django-insecure-4rman5(hp!xg5)h@x&60gvh4!7^)he(7u2g-nb)%ngeowbxiad"

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

# Development: when DEBUG is True, allow connections from Docker and local networks
# - Docker Desktop on Windows exposes the host as `host.docker.internal` inside containers.
# - For quick local testing we allow all hosts when DEBUG=True. In production set strict ALLOWED_HOSTS.
if DEBUG:
    ALLOWED_HOSTS = ["*"]
else:
    ALLOWED_HOSTS = ["127.0.0.1", "localhost", "stirling.ramaqs.com", "localhost:5174"]



# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",

    # cors
    "corsheaders",
    #  Added apps
    "rest_framework",
    "rest_framework.authtoken",
    "django_filters",
    "drf_yasg",
    "users",
    "documents",
    "workflows",

    # Storage
    'minio_storage',
]

REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": [
        "rest_framework.authentication.TokenAuthentication",
        "rest_framework.authentication.SessionAuthentication",
    ],
    "DEFAULT_PERMISSION_CLASSES": [
        "rest_framework.permissions.IsAuthenticated",
    ],
}


MIDDLEWARE = [
    "corsheaders.middleware.CorsMiddleware",
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    # Removed CommonMiddleware to avoid early Invalid HTTP_HOST parsing of malformed host headers in development.
    # If you fix the client Host header to a valid value (e.g. "localhost:8000") you can re-enable it.
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "backend.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "backend.wsgi.application"


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

# Load environment variables from .env file
load_dotenv()

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.postgresql",
        "NAME": os.getenv("DB_NAME"),  # PostgreSQL database name from .env
        "USER": os.getenv("DB_USER"),  # PostgreSQL username from .env
        "PASSWORD": os.getenv("DB_PASSWORD"),  # PostgreSQL password from .env
        "HOST": os.getenv("DB_HOST", "localhost"),  # Default to localhost if not set
        "PORT": os.getenv("DB_PORT", "5432"),  # Default PostgreSQL port if not set
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = "static/"

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"
# Minio / S3 Storage configuration
# All file storage is handled by MinioMediaStorage, ensuring files are stored in Minio/S3.
# The storage backend is configured here; do not pass storage instances into model fields
# because migrations will serialize them. Use relative upload paths (upload_to) in models.


# --------------------------------------------------------------------
# STATIC FILES
# --------------------------------------------------------------------
STATIC_URL = "static/"
STATIC_ROOT = './static_files/'

# --------------------------------------------------------------------
# MINIO CONFIGURATION
# --------------------------------------------------------------------
MINIO_STORAGE_ENDPOINT = "s3.ramaqs.com"  # NO http:// prefix
MINIO_STORAGE_ACCESS_KEY = os.getenv("MINIO_ACCESS_KEY", "wWdV6G6VSoG7KBHQprVl")
MINIO_STORAGE_SECRET_KEY = os.getenv("MINIO_SECRET_KEY", "nKTDOM5I6lxYqnzo1K6QqDBXn9M8S1dGFESH2uEz")
MINIO_STORAGE_USE_HTTPS = False

# Bucket configuration
MINIO_STORAGE_MEDIA_BUCKET_NAME = "smartdocspro"
MINIO_STORAGE_AUTO_CREATE_MEDIA_BUCKET = True
MINIO_STORAGE_AUTO_CREATE_STATIC_BUCKET = True

# Optional: Direct MinIO URLs for serving files
MINIO_STORAGE_MEDIA_URL = "s3.ramaqs.com"

# --------------------------------------------------------------------
# STORAGE BACKENDS (Django 4.2+)
# --------------------------------------------------------------------
# This is the NEW way to configure storage in Django 4.2+
STORAGES = {
    "default": {
        "BACKEND": "minio_storage.storage.MinioMediaStorage",
    },
    "staticfiles": {
        "BACKEND": "django.contrib.staticfiles.storage.StaticFilesStorage",
    },
}

# Development-friendly MEDIA_ROOT fallback so files saved by the callback
# go to a local `media/` directory when DEBUG is enabled. In production the
# MinIO storage backend will be used as configured above.
if DEBUG:
    MEDIA_ROOT = os.path.join(BASE_DIR, "media")
    # Ensure MEDIA_URL is defined for local development
    MEDIA_URL = "/media/"

# ONLYOFFICE JWT secret used to sign document config tokens when Document Server
# requires JWT. In development you can set this here or export ONLYOFFICE_JWT_SECRET
# in your environment. For production, prefer setting an env var instead of
# committing secrets to source control.
ONLYOFFICE_JWT_SECRET = os.getenv("ONLYOFFICE_JWT_SECRET", "xnxsezWUInkVkg2veAKTechnmI803B3L")

# --------------------------------------------------------------------
# LEGACY STORAGE SETTING (for Django < 4.2)
# --------------------------------------------------------------------
# If the STORAGES dict above doesn't work, uncomment this line:
# DEFAULT_FILE_STORAGE = "minio_storage.storage.MinioMediaStorage"

CORS_ALLOWED_ORIGINS = [
    "http://localhost:5173",
]
CORS_ALLOW_CREDENTIALS = True


# EMAIL CONFIGURATION
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = 'ramaqshse@gmail.com'
EMAIL_HOST_PASSWORD = 'qxmoirdbbofimvtv'
DEFAULT_FROM_EMAIL = EMAIL_HOST_USER
