# Generated by Django 5.1.5 on 2025-10-04 15:37

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_title', models.CharField(max_length=1024)),
                ('doc_type', models.CharField(max_length=50)),
                ('doc_creation_date', models.DateTimeField(auto_now_add=True)),
                ('doc_modification_date', models.DateTimeField(auto_now=True)),
                ('doc_path', models.FileField(max_length=2048, upload_to='documents/')),
                ('doc_status', models.CharField(max_length=50)),
                ('doc_size', models.FloatField()),
                ('doc_format', models.CharField(max_length=20)),
                ('doc_category', models.CharField(max_length=50)),
                ('doc_description', models.TextField()),
                ('doc_comment', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='DocumentVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version_number', models.IntegerField()),
                ('version_date', models.DateTimeField(auto_now_add=True)),
                ('version_path', models.FileField(max_length=255, upload_to='uploads/')),
                ('version_comment', models.TextField(blank=True)),
            ],
        ),
    ]
