# Generated by Django 5.1.4 on 2025-01-07 15:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255)),
                ('type', models.CharField(max_length=50)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('date_suppression', models.DateTimeField(blank=True, null=True)),
                ('statut', models.CharField(max_length=50)),
                ('taille', models.FloatField()),
                ('format', models.CharField(max_length=20)),
                ('categorie', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('commentaire', models.TextField(blank=True)),
                ('role_user', models.CharField(max_length=50)),
                ('role_departement', models.CharField(max_length=50)),
                ('departement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.departement')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
