# Generated by Django 5.1.4 on 2025-02-09 15:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('documents', '0001_initial'),
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='doc_departement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.departement'),
        ),
        migrations.AddField(
            model_name='document',
            name='doc_owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
