# Generated by Django 5.1.5 on 2025-10-06 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='doc_path',
            field=models.FileField(upload_to='documents/'),
        ),
    ]
