# Generated by Django 5.1.5 on 2025-10-06 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0003_alter_document_doc_path'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='doc_path',
            field=models.FileField(max_length=2048, upload_to='documents/'),
        ),
        migrations.AlterField(
            model_name='documentversion',
            name='version_path',
            field=models.FileField(max_length=255, upload_to='documents/versions/'),
        ),
    ]
