# Generated by Django 5.1.5 on 2025-10-26 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0005_document_created_at_document_updated_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='doc_type',
        ),
        migrations.AlterField(
            model_name='document',
            name='doc_status',
            field=models.CharField(choices=[('draft', 'Draft'), ('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], max_length=50),
        ),
    ]
