# Generated by Django 5.1.5 on 2025-10-26 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0006_remove_document_doc_type_alter_document_doc_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='doc_category',
        ),
        migrations.RemoveField(
            model_name='document',
            name='doc_creation_date',
        ),
        migrations.RemoveField(
            model_name='document',
            name='doc_modification_date',
        ),
    ]
