# Generated by Django 5.1.5 on 2025-10-26 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0007_remove_document_doc_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='doc_type',
            field=models.CharField(default='docx', max_length=50),
            preserve_default=False,
        ),
    ]
