# Generated by Django 5.1.5 on 2025-10-26 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0008_document_doc_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='doc_comment',
        ),
        migrations.AlterField(
            model_name='document',
            name='doc_status',
            field=models.CharField(choices=[('draft', 'Draft'), ('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('archived', 'Archived')], max_length=50),
        ),
    ]
