# Generated by Django 5.1.5 on 2025-11-15 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0009_remove_document_doc_comment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='doc_path',
            field=models.FileField(max_length=2048, upload_to=''),
        ),
    ]
