# Generated by Django 5.1.5 on 2025-12-18 22:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0011_documentcategory_documentnature_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='documentdistribution',
            name='document_version',
        ),
        migrations.RemoveField(
            model_name='documentdistribution',
            name='recipient',
        ),
        migrations.RemoveField(
            model_name='documentversion',
            name='approved_by',
        ),
        migrations.RemoveField(
            model_name='documentversion',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='documentversion',
            name='document',
        ),
        migrations.RemoveField(
            model_name='documentversion',
            name='verified_by',
        ),
        migrations.RemoveField(
            model_name='document',
            name='current_version',
        ),
        migrations.RemoveField(
            model_name='document',
            name='doc_status',
        ),
        migrations.RemoveField(
            model_name='document',
            name='is_archived',
        ),
        migrations.RemoveField(
            model_name='document',
            name='last_reviewed_at',
        ),
        migrations.RemoveField(
            model_name='document',
            name='next_review_due',
        ),
        migrations.AlterField(
            model_name='document',
            name='doc_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='documents.documentcategory'),
        ),
        migrations.AlterField(
            model_name='document',
            name='doc_code',
            field=models.CharField(db_index=True, default=2, max_length=20, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='document',
            name='doc_nature',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='documents.documentnature'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='document',
            name='doc_status_type',
            field=models.CharField(choices=[('ORIGINAL', 'Original'), ('COPIE', 'Copie'), ('PERIME', 'Périmé')], default='ORIGINAL', max_length=10),
        ),
        migrations.AlterField(
            model_name='document',
            name='parent_document',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='documents.document'),
        ),
        migrations.AlterField(
            model_name='document',
            name='sequential_number',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='DocumentArchive',
        ),
        migrations.DeleteModel(
            name='DocumentDistribution',
        ),
        migrations.DeleteModel(
            name='DocumentVersion',
        ),
    ]
