# Generated by Django 5.1.5 on 2025-12-20 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0013_documentversion_folder'),
    ]

    operations = [
        migrations.AlterField(
            model_name='folder',
            name='fol_path',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
    ]
