# Generated by Django 5.1.5 on 2025-12-20 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0014_alter_folder_fol_path'),
    ]

    operations = [
        migrations.AlterField(
            model_name='folder',
            name='fol_path',
            field=models.CharField(default=1, max_length=1024),
            preserve_default=False,
        ),
    ]
