# Generated by Django 5.1.5 on 2025-12-20 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0015_alter_folder_fol_path'),
    ]

    operations = [
        migrations.AlterField(
            model_name='folder',
            name='fol_name',
            field=models.CharField(max_length=255),
        ),
    ]
