# Generated by Django 5.1.5 on 2025-12-20 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0017_folder_unique_name_in_parent'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='folder',
            name='unique_folder_name_in_parent',
        ),
        migrations.RemoveField(
            model_name='document',
            name='doc_category',
        ),
        migrations.RemoveField(
            model_name='document',
            name='doc_nature',
        ),
        migrations.AlterField(
            model_name='folder',
            name='fol_index',
            field=models.CharField(default='GD', max_length=5),
        ),
    ]
