# Generated by Django 5.1.5 on 2025-12-20 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0018_remove_folder_unique_folder_name_in_parent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='folder',
            name='fol_order',
            field=models.PositiveIntegerField(blank=True, help_text='Order of PR folders within the parent folder', null=True),
        ),
    ]
