# Generated by Django 5.1.5 on 2025-12-20 11:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0018_default_doc_nature'),
        ('documents', '0019_folder_fol_order'),
    ]

    operations = [
    ]
