# Generated by Django 5.1.5 on 2025-12-20 12:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0020_merge_0018_default_doc_nature_0019_folder_fol_order'),
    ]

    operations = [
        migrations.RenameField(
            model_name='document',
            old_name='sequential_number',
            new_name='doc_nature_order',
        ),
        migrations.AddField(
            model_name='document',
            name='doc_nature',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='documents.documentnature'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='documentnature',
            name='code',
            field=models.CharField(max_length=2, unique=True),
        ),
    ]
