# Generated by Django 5.1.5 on 2025-12-20 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0021_rename_sequential_number_document_doc_nature_order_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='doc_size',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
