# Generated by Django 5.1.5 on 2025-12-20 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0022_alter_document_doc_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='doc_nature_order',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
