# Generated by Django 5.1.5 on 2025-12-20 12:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0023_alter_document_doc_nature_order'),
    ]

    operations = [
        migrations.RenameField(
            model_name='document',
            old_name='doc_nature',
            new_name='doc_nature_id',
        ),
    ]
