# Generated by Django 5.1.5 on 2025-12-20 12:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0024_rename_doc_nature_document_doc_nature_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='document',
            old_name='doc_nature_id',
            new_name='doc_nature',
        ),
    ]
