# Generated by Django 5.1.5 on 2025-12-22 18:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0025_rename_doc_nature_id_document_doc_nature'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='parent_folder',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='documents.folder'),
            preserve_default=False,
        ),
    ]
