# Generated by Django 5.1.5 on 2025-12-30 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0026_document_parent_folder'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='mlean_document_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='mlean_paper_standard_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='mlean_standard_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
