# Generated by Django 5.1.5 on 2025-12-31 13:44

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0027_document_mlean_document_id_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='documentversion',
            options={'ordering': ['-version_number', '-version_date']},
        ),
        migrations.AddField(
            model_name='documentversion',
            name='change_type',
            field=models.CharField(choices=[('MINOR', 'Minor changes'), ('AUDITABLE', 'Auditable')], default='MINOR', max_length=20),
        ),
        migrations.AddField(
            model_name='documentversion',
            name='mlean_document_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='documentversion',
            name='mlean_paper_standard_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='documentversion',
            name='mlean_standard_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddConstraint(
            model_name='documentversion',
            constraint=models.UniqueConstraint(fields=('document', 'version_number'), name='uniq_document_version_number'),
        ),
        migrations.AddConstraint(
            model_name='folder',
            constraint=models.UniqueConstraint(fields=('fol_name', 'parent_folder'), name='unique_folder_name_in_parent'),
        ),
    ]
