# Generated by Django 5.1.5 on 2026-01-01 22:21

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0028_alter_documentversion_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentArchive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archived_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('retention_until', models.DateTimeField(blank=True, null=True)),
                ('restored_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('ACTIVE', 'ACTIVE'), ('RESTORED', 'RESTORED'), ('EXPIRED', 'EXPIRED')], default='ACTIVE', max_length=10)),
                ('note', models.TextField(blank=True, default='')),
            ],
            options={
                'ordering': ['-archived_at'],
            },
        ),
        migrations.RemoveConstraint(
            model_name='documentversion',
            name='uniq_document_version_number',
        ),
        migrations.RemoveField(
            model_name='documentversion',
            name='mlean_document_id',
        ),
        migrations.RemoveField(
            model_name='documentversion',
            name='mlean_paper_standard_id',
        ),
        migrations.RemoveField(
            model_name='documentversion',
            name='mlean_standard_id',
        ),
        migrations.AddField(
            model_name='document',
            name='archived_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='archived_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='archived_documents', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='document',
            name='archived_until',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='is_archived',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='document',
            name='doc_description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='document',
            name='mlean_document_id',
            field=models.IntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='document',
            name='mlean_paper_standard_id',
            field=models.IntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='document',
            name='mlean_standard_id',
            field=models.IntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='documentcategory',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='documentnature',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='documentversion',
            name='change_type',
            field=models.CharField(choices=[('MINOR', 'Minor'), ('AUDITABLE', 'Auditable')], default='MINOR', max_length=10),
        ),
        migrations.AlterField(
            model_name='documentversion',
            name='version_comment',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='documentversion',
            name='version_path',
            field=models.FileField(max_length=2048, upload_to='documents/versions/'),
        ),
        migrations.AlterField(
            model_name='folder',
            name='fol_path',
            field=models.CharField(blank=True, default='', max_length=1024),
        ),
        migrations.AddConstraint(
            model_name='documentversion',
            constraint=models.UniqueConstraint(fields=('document', 'version_number'), name='unique_version_per_document'),
        ),
        migrations.AddField(
            model_name='documentarchive',
            name='archived_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='document_archive_actions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='documentarchive',
            name='document',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='archive_records', to='documents.document'),
        ),
        migrations.AddIndex(
            model_name='documentarchive',
            index=models.Index(fields=['status'], name='documents_d_status_a7222e_idx'),
        ),
        migrations.AddIndex(
            model_name='documentarchive',
            index=models.Index(fields=['retention_until'], name='documents_d_retenti_4e8960_idx'),
        ),
    ]
