# Generated by Django 5.1.5 on 2026-01-02 01:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0029_documentarchive_and_more'),
        ('users', '0005_permissionaudit'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='archive_note',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='folder',
            name='archived_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='folder',
            name='archived_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='archived_folders', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='folder',
            name='archived_note',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='folder',
            name='archived_until',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='folder',
            name='is_archived',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='folder',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['is_archived'], name='documents_d_is_arch_a568c1_idx'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['archived_until'], name='documents_d_archive_b4c234_idx'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['mlean_document_id'], name='documents_d_mlean_d_e60ed0_idx'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['mlean_paper_standard_id'], name='documents_d_mlean_p_e35539_idx'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['mlean_standard_id'], name='documents_d_mlean_s_bc0874_idx'),
        ),
        migrations.AddIndex(
            model_name='documentarchive',
            index=models.Index(fields=['archived_at'], name='documents_d_archive_171c29_idx'),
        ),
        migrations.AddIndex(
            model_name='folder',
            index=models.Index(fields=['is_archived'], name='documents_f_is_arch_fcc769_idx'),
        ),
        migrations.AddIndex(
            model_name='folder',
            index=models.Index(fields=['archived_until'], name='documents_f_archive_ea3741_idx'),
        ),
    ]
