# Generated by Django 5.1.5 on 2026-01-03 15:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0030_document_archive_note_folder_archived_at_and_more'),
        ('users', '0005_permissionaudit'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentSite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True)),
                ('name', models.CharField(max_length=128)),
                ('description', models.TextField(blank=True, default='')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Document Site',
                'verbose_name_plural': 'Document Sites',
                'ordering': ['code', 'name'],
            },
        ),
        migrations.CreateModel(
            name='DocumentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True)),
                ('name', models.CharField(max_length=128)),
                ('description', models.TextField(blank=True, default='')),
                ('last_index', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Document Type',
                'verbose_name_plural': 'Document Types',
                'ordering': ['code', 'name'],
            },
        ),
        migrations.AddField(
            model_name='document',
            name='doc_type_index',
            field=models.PositiveIntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='document',
            name='doc_code',
            field=models.CharField(db_index=True, max_length=50, unique=True),
        ),
        migrations.AddField(
            model_name='document',
            name='doc_site',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='documents.documentsite'),
        ),
        migrations.AddField(
            model_name='document',
            name='doc_type_ref',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='documents.documenttype'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['doc_type_ref', 'doc_type_index'], name='documents_d_doc_typ_12a9d6_idx'),
        ),
        migrations.AddConstraint(
            model_name='document',
            constraint=models.UniqueConstraint(fields=('doc_type_ref', 'doc_type_index'), name='unique_doc_type_index_per_type'),
        ),
    ]
