# Generated by Django 5.1.5 on 2026-01-03 15:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0031_documentsite_documenttype_document_doc_type_index_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='document',
            name='doc_site',
        ),
        migrations.AlterModelOptions(
            name='documenttype',
            options={},
        ),
        migrations.RemoveConstraint(
            model_name='document',
            name='unique_doc_type_index_per_type',
        ),
        migrations.RemoveIndex(
            model_name='document',
            name='documents_d_doc_typ_12a9d6_idx',
        ),
        migrations.RemoveField(
            model_name='document',
            name='doc_type_index',
        ),
        migrations.RemoveField(
            model_name='document',
            name='doc_type_ref',
        ),
        migrations.RemoveField(
            model_name='documenttype',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='documenttype',
            name='last_index',
        ),
        migrations.AddField(
            model_name='document',
            name='document_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='documents.documenttype'),
        ),
        migrations.AddField(
            model_name='document',
            name='document_type_order',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='document',
            name='doc_code',
            field=models.CharField(db_index=True, max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='documenttype',
            name='code',
            field=models.CharField(help_text='Prefix for document index (e.g. PROC, MAN)', max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='documenttype',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AddField(
            model_name='document',
            name='site',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='documents.site'),
        ),
        migrations.DeleteModel(
            name='DocumentSite',
        ),
    ]
