# Generated by Django 5.1.5 on 2026-01-04 21:19

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0032_site_remove_document_doc_site_and_more'),
        ('users', '0005_permissionaudit'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='workflow_status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('PENDING_REVIEW', 'Pending Review'), ('IN_REVIEW', 'In Review'), ('REJECTED', 'Rejected'), ('PENDING_APPROVAL', 'Pending Approval'), ('APPROVED', 'Approved'), ('PUBLISHED', 'Published')], db_index=True, default='DRAFT', max_length=20),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['workflow_status'], name='documents_d_workflo_6181d1_idx'),
        ),
    ]
