# Generated by Django 5.1.5 on 2026-01-04 21:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0033_document_workflow_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='doc_nature',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='documents.documentnature'),
        ),
    ]
