# Generated by Django 5.1.5 on 2026-01-04 21:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0034_alter_document_doc_nature'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='document',
            name='documents_d_workflo_6181d1_idx',
        ),
        migrations.RemoveField(
            model_name='document',
            name='workflow_status',
        ),
        migrations.AlterField(
            model_name='document',
            name='doc_nature',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='documents.documentnature'),
        ),
    ]
