# Generated by Django 5.1.5 on 2026-01-09 00:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0035_remove_document_documents_d_workflo_6181d1_idx_and_more'),
        ('users', '0006_site_alter_departement_dep_name_departement_site_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='site',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.site'),
        ),
        migrations.DeleteModel(
            name='Site',
        ),
    ]
