# Generated by Django 5.1.5 on 2026-01-09 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0036_alter_document_site_delete_site'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='doc_status_type',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('PUBLIC', 'Public'), ('ORIGINAL', 'Original'), ('COPIE', 'Copie'), ('PERIME', 'Périmé')], default='DRAFT', max_length=20),
        ),
    ]
