# Generated by Django 5.1.5 on 2026-01-10 22:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0037_alter_document_doc_status_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='document',
            options={'permissions': [('can_create_cross_department', 'Can create documents in any department')]},
        ),
    ]
