# Generated by Django 5.1.5 on 2026-01-10 23:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0038_alter_document_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='Unique code identifier (e.g., QUA-001)', max_length=50, unique=True)),
                ('name', models.CharField(help_text='Display name for the code', max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('is_active', models.BooleanField(default=True, help_text='Only active codes appear in selection')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Document Code',
                'verbose_name_plural': 'Document Codes',
                'ordering': ['code'],
            },
        ),
        migrations.AddField(
            model_name='document',
            name='document_code',
            field=models.ForeignKey(blank=True, help_text='Predefined document code selected by user', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents', to='documents.documentcode'),
        ),
    ]
