# Generated by Django 5.1.5 on 2025-10-25 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_useractionlog'),
    ]

    operations = [
        migrations.RenameField(
            model_name='departement',
            old_name='dep_type',
            new_name='dep_color',
        ),
        migrations.RenameField(
            model_name='role',
            old_name='role_type',
            new_name='role_color',
        ),
        migrations.AlterField(
            model_name='departement',
            name='dep_name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='role',
            name='role_name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
