# Generated by Django 5.1.5 on 2026-01-09 00:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_permissionaudit'),
    ]

    operations = [
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='departement',
            name='dep_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AddField(
            model_name='departement',
            name='site',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='departements', to='users.site'),
        ),
        migrations.AlterUniqueTogether(
            name='departement',
            unique_together={('dep_name', 'site')},
        ),
    ]
